export default {

PROFILES_RECEIVED: 'PROFILES_RECEIVED',

TASKS_RECIEVED: 'TASKS_RECIEVED',
TASK_CREATED: 'TASK_CREATED',
CATEGORY_SELECTED: 'CATEGORY_SELECTED',


PROFILE_CREATED: 'PROFILE_CREATED',
USER_LOGGED_IN: 'USER_LOGGED_IN',

MESSAGE_CREATED: 'MESSAGE_CREATED',
MESSAGE_RECIEVED: 'MESSAGE_RECIEVED'





}
